# sudo docker-compose -f ~/docker/shellcrash/compose.yaml up -d

services:
  shellcrash:
    image: shellcrash:latest
    container_name: shellcrash
    hostname: shellcrash
    network_mode: bridge
    restart: unless-stopped
#    networks:
#      macvlan_lan:
#        ipv4_address: 10.0.0.9
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - NET_RAW
    ports:
      - 7890:7890     #代理端口
      - 9999:9999     #zhashboard
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      net.ipv4.ip_forward: 1
    volumes:
      - ~/docker/shellcrash:/etc/ShellCrash

#  macvlan:
#    external: true