# sudo docker-compose -f ~/docker/shellcrash/compose.yaml up -d

services:
  shellcrash:
    image: naspilot/shellcrash:dev
    container_name: shellcrash
    hostname: shellcrash
    network_mode: bridge
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - NET_RAW
    ports:
      - 7890:7890     #代理端口
      - 9999:9999     #面板端口
    volumes:
      - ~/docker/shellcrash:/etc/ShellCrash

#    sysctls:
#      net.ipv4.ip_forward: 1
#    devices:
#      - /dev/net/tun:/dev/net/tun
#    networks:
#      macvlan_lan:
#        ipv4_address: 10.0.0.9
#  macvlan:
#    external: true